Repository ucsd-cse125-sp25/group1, pull requests merged in 2025-05, with the labels that each got.

#35 Integrate components into server and client
  include/client/components/door.hpp
  include/client/components/interactable.hpp
  include/client/components/object.hpp
  include/client/components/room.hpp
  include/server/components/door.hpp
  include/server/components/interactable.hpp
  include/server/components/object.hpp
  include/server/components/room.hpp
  include/server/player.hpp
  src/client/components/door.cpp
  src/client/components/interactable.cpp
  src/client/components/object.cpp
  src/client/components/room.cpp
  src/server/components/door.cpp
  src/server/components/interactable.cpp
  src/server/components/object.cpp
  src/server/components/room.cpp
  src/server/player.cpp
  src/server/server.cpp
Labels: general

#50 Resize AABB on rotation + diagonal velocity fixed
  include/server/player.hpp
  include/server/rigidBody.hpp
  src/server/collisionSolver.cpp
  src/server/player.cpp
  src/server/rigidBody.cpp
  src/server/server.cpp
Labels: bug, enhancement, physics

#55 File for Initializing Rigid Bodies
  include/server/components/door.hpp
  include/server/components/frog.hpp
  include/server/components/interactable.hpp
  include/server/components/object.hpp
  include/server/components/water.hpp
  include/server/initBody.hpp
  include/server/rigidBody.hpp
  include/server/server.hpp
  src/server/components/door.cpp
  src/server/components/frog.cpp
  src/server/components/interactable.cpp
  src/server/components/object.cpp
  src/server/components/water.cpp
  src/server/initBody.cpp
  src/server/player.cpp
  src/server/server.cpp
  src/server/swamp.cpp
Labels: enhancement, physics, general

#67 Adjusted bounding boxes to prevent clipping through floor on respawn
  src/client/models/swamp_room.obj
  src/server/data/dimensions.json
  src/server/data/layout.json
Labels: bug, physics

#68 Cannonball Physics
  include/server/components/cannonball.hpp
  include/shared/config.hpp
  src/server/components/cannonball.cpp
Labels: physics, mini-game

#69 Piano keys
  include/server/components/pianoKey.hpp
  src/server/components/pianoKey.cpp
Labels: physics, mini-game
